### ISSUE TITLE
recognize spot market instances, label/taint them on decomission status

### ISSUE THREAD

**Issue by flokli** [kubernetes-sigs/cloud-provider-equinix-metal#182]
For less stateful workloads, it might be useful to use spot instances.

However, as these can be [revoked with a 2 minutes notice at any time](
https://metal.equinix.com/developers/docs/deploy/spot-market/), the cluster needs to know about the fact nodes being spot instances, and nodes that are decommissioned.

The CCM should label spot instance nodes accordingly, and when they're about to be decomissioned, taint them (so workloads can be migrated away).

There's the `node.cloudprovider.kubernetes.io/shutdown ` taint for these purposes.

~Other than that, considering that node is not coming back, it could also remove the Node object from the cluster entirely.~

**Comment by deitch** [comment]
> considering that node is not coming back, it could also remove the Node object from the cluster entirely.

The CCM already does that. Once a node disappears, the CCM checks if the node is valid and, if it is gone, removes it. This isn't an EQXM implementation thing; it is part of CCM in general.

> The CCM should label spot instance nodes accordingly

What label would you use? Who would consume that label?

> when they're about to be decommissioned, taint them (so workloads can be migrated away).

This I like. I don't know how we would catch it, though. The EQXM API doesn't have a push-driven event system, like k8s does. If we could come up with a sane way to do this, I would like to. Do any of the CCMs from other cloud providers have these capabilities that we could learn from?

**Comment by displague** [comment]
@deitch with the current polling, could we take advantage of the [TTL field](https://metal.equinix.com/developers/docs/deploy/spot-market/#spot-market-termination) and taint nodes within some specified window? We would want to be flexible (configurable) with this. I will create devices with a one week TTL, for example, and I wouldn't want to see those cordoned.

I wonder if polling the metadata service might be lighter weight, allowing for more frequent polling than API polling, but I wouldn't want to add to #183.

**Comment by deitch** [comment]
> I wonder if polling the metadata service might be lighter weight

It might, but it only would give information on the node on which CCM is running, and not all of the other nodes. For that, EQXM API is meant to be used (and there isn't really anything available in metadata that _isn't_ in the API).

> could we take advantage of the TTL field

TTL field? I thought spot market instances are just that, spot market, and that they can be terminated anytime with 120 seconds warning?

So let me see if I get this.

1. When CCM sees a new node, it also checks if it is spot market and, if so, adds a taint or annotation
2. On each CCM cycle(currently 60 seconds), check each node that was tainted/annotated as "from the spot market" to see if it has been marked for termination (it should be anywhere from 0-60 seconds in, given that the CCM loop is 60 seconds, but there is likely to be at least a little drift there).
3. For each node marked as "in termination window", taint so that k8s control plane migrates nodes off of it

Is that it? It is far from perfect, but may be the best doable. 

I have a few concerns:

* EQXM API does not have a multi-get ("get all devices with the IDs 1,2,3,6,25"), it only has "list all for project" or "get a single one", so we would either get all of them (which could be a lot) or lots of queries, which is likely to be slow; by the time we are done, we may already be ¾ of the way through our 120 second window 
* Are we over-engineering this? Kubernetes is designed to reschedule workloads when nodes disappear. At a certain point, we will do significant amounts of work to try and catch workloads and tell kubernetes to try and move them seconds before the node goes belly up anyways

**Comment by displague** [comment]
> EQXM API does not have a multi-get ("get all devices with the IDs 1,2,3,6,25"), it only has "list all for project" or "get a single one", so we would either get all of them (which could be a lot) or lots of queries, which is likely to be slow; by the time we are done, we may already be ¾ of the way through our 120 second window

If we use the exclude query parameters (GetOptions Exclude), we can remove the SSH keys and perhaps some other unused optional response components, this typically speeds up the response.

> check each node that was tainted/annotated as "from the spot market" to see if it has been marked for termination 

Any node (on-demand or spot) can be created with a termination time. I don't know if this will appear in the `/2009-04-04/meta-data/spot/termination-time`, but it will show up in `Device.TerminationTime`. 

For on-demand nodes, we may have a considerably larger window of time to act.

> Are we over-engineering this? 

I would naively imagine the PR would look like this:
* an extra node annotation alongside other annotations based on Device API response values 
* an extra device state to be aware of when reporting that a machine is scheduled for shut down or maintenance

However, 
- I don't see evidence of a cloud provider spec way to set arbitrary node annotations
- I don't see evidence of a scheduling concept in the cloud provider (nor the spec)

I'll have to take a deeper look to say.

**Comment by deitch** [comment]
> I don't see evidence of a cloud provider spec way to set arbitrary node annotations

There isn't, but we do it here anyways. We set all sorts of annotations on the nodes in CPEM. That isn't a blocker.

> I don't see evidence of a scheduling concept in the cloud provider (nor the spec)

Again, there isn't, but we do it here anyways. We start a separate goroutine and have a 60 second loop.

> If we use the exclude query parameters (GetOptions Exclude), we can remove the SSH keys and perhaps some other unused optional response components, this typically speeds up the response.

Are you talking about list or multiple get?

> Any node (on-demand or spot) can be created with a termination time

I am not sure I understand. Are you suggesting that, with each node, we check if it has a termination time, and if it does, that is an indication that it will be terminated at that time? That "termination time" might be because we explicitly told it to be so at that time when creating, or because it was a spot market instance that the EQXM API decided to terminate (the "120 second warning")?

**Comment by flokli** [comment]
> > Any node (on-demand or spot) can be created with a termination time
>  I am not sure I understand. Are you suggesting that, with each node, we check if it has a termination time, and if it does, that is an indication that it will be terminated at that time? That "termination time" might be because we explicitly told it to be so at that time when creating, or because it was a spot market instance that the EQXM API decided to terminate (the "120 second warning")?

The fact it is a spot instance could probably be a label, so less persistent workloads can be scheduled on it.

> @deitch with the current polling, could we take advantage of the TTL field and taint nodes within some specified window? We would want to be flexible (configurable) with this. I will create devices with a one week TTL, for example, and I wouldn't want to see those cordoned

Agreed on this. When the taint is added (how long before termination) could be a configuration option.
